name: Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_frontend:
    name: Build Frontend (Mock)
    runs-on: ubuntu-latest
    steps:
      - name: Mock build step
        run: |
          echo "Mock: Building Angular frontend..."

  build_backend_images:
    name: Build Backend (Mock)
    runs-on: ubuntu-latest
    steps:
      - name: Mock build images
        run: |
          echo "Mock: Building Docker image for Gateway..."
          echo "Mock: Building Docker image for Srv.Admin.Web.Host..."
          echo "Mock: Building Docker image for Srv.Identity.Web.Host..."

  deploy_frontend:
    name: Deploy Frontend (Mock)
    runs-on: ubuntu-latest
    needs: build_frontend
    if: github.event_name != 'workflow_dispatch' || success()
    steps:
      - name: Mock deploy step
        run: |
          echo "Mock: Deploying Angular frontend..."

  deploy_backend:
    name: Deploy Backend (Mock)
    runs-on: ubuntu-latest
    needs: build_backend_images
    steps:
      - name: Mock deploy step
        run: |
          echo "Mock: Deploying backend services..."